id: IF7D66DEE
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:23:38+00:00'
last_modified: '2022-06-10T11:08:40.738504+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27509
  title: རྔོག་ལོ་ཙཱ་བ་བློ་ལྡན་ཤེས་རབ་ཀྱི་རྣམ་ཐར
  volume:
    2a1c8174cc5e459c9ae8d5b25b8d9f52:
      image_group_id: I5258
      title: ''
      volume_number: 1
      total_pages: 50
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    499E:
      image_group_id: I5258
      title: ''
      total_pages: 50
      order: 1
      base_file: 499E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
